### ISSUE TITLE
"Cannot Create Raw Socket" How to fix?

### ISSUE THREAD

**Issue by Elforget** [MHProDev/MHDDoS#197]
When using some Layer4 methods, "Cannot Create Raw Socket" appears, what is the problem?
![image](https://user-images.githubusercontent.com/45536046/156903874-d626a195-f5e8-44ee-a9bd-ed33daf2b414.png)

**Comment by MHProDev** [comment]
run using sudo (this method only with spoofable servers)

**Comment by TonyLCH** [comment]
> run using sudo (this method only with spoofable servers)

I have the same problem,but run sudo command still doesn't work

**Comment by sova32** [comment]
vadiki@localhost:/run/media/vadiki/D_238_GB_WD/Кибервойска/DDoS/MHDDoS_proxy/MHDDoS> pip3 install pyroxy
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyroxy in /home/vadiki/.local/lib/python3.8/site-packages (1.0b4)
Requirement already satisfied: maxminddb>=2.2.0 in /home/vadiki/.local/lib/python3.8/site-packages (from pyroxy) (2.2.0)
Requirement already satisfied: pysocks>=1.7.1 in /usr/lib/python3.8/site-packages (from pyroxy) (1.7.1)
Requirement already satisfied: requests>=2.27.1 in /usr/lib/python3.8/site-packages (from pyroxy) (2.27.1)
Requirement already satisfied: yarl>=1.7.2 in /home/vadiki/.local/lib/python3.8/site-packages (from pyroxy) (1.7.2)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3.8/site-packages (from requests>=2.27.1->pyroxy) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3.8/site-packages (from requests>=2.27.1->pyroxy) (1.26.7)
Requirement already satisfied: charset_normalizer~=2.0.0 in /usr/lib/python3.8/site-packages (from requests>=2.27.1->pyroxy) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3.8/site-packages (from requests>=2.27.1->pyroxy) (3.3)
Requirement already satisfied: multidict>=4.0 in /home/vadiki/.local/lib/python3.8/site-packages (from yarl>=1.7.2->pyroxy) (6.0.2)
vadiki@localhost:/run/media/vadiki/D_238_GB_WD/Кибервойска/DDoS/MHDDoS_proxy/MHDDoS> sudo pip3 install pyroxy
[sudo] пароль для root: 
Requirement already satisfied: pyroxy in /usr/local/lib/python3.8/site-packages (0.1)
Requirement already satisfied: bottle in /usr/local/lib/python3.8/site-packages (from pyroxy) (0.12.19)
Requirement already satisfied: lxml in /usr/local/lib64/python3.8/site-packages (from pyroxy) (4.8.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
vadiki@localhost:/run/media/vadiki/D_238_GB_WD/Кибервойска/DDoS/MHDDoS_proxy/MHDDoS> sudo python3 start.py dns 185.63.191.14:53 256 600 resolvers.txt
Traceback (most recent call last):
  File "start.py", line 27, in <module>
    from PyRoxy import Proxy, ProxyChecker, ProxyType, ProxyUtiles
ModuleNotFoundError: No module named 'PyRoxy'
vadiki@localhost:/run/media/vadiki/D_238_GB_WD/Кибервойска/DDoS/MHDDoS_proxy/MHDDoS> python3 --version
Python 3.8.12
vadiki@localhost:/run/media/vadiki/D_238_GB_WD/Кибервойска/DDoS/MHDDoS_proxy/MHDDoS> python3 start.py dns 185.63.191.14:53 256 600 resolvers.txt
[16:45:57 - ERROR] Cannot Create Raw Socket
vadiki@localhost:/run/media/vadiki/D_238_GB_WD/Кибервойска/DDoS/MHDDoS_proxy/MHDDoS>
